global:
  variables:
  - DOCKER_PUSH=true
  - DIRECTORY=generated

tasks:
  languages:
    steps:
    - checkout
    - run: bundle install
    - run: |
        LANGUAGES=($(ls -d $DIRECTORY/*))
        LANGPATH=${LANGUAGES[ $RANDOM % ${#LANGUAGES[@]} ]}
        LANG="$(basename ${LANGPATH})"
        test -n "$LANG"
        echo "Building images for $LANG"

        sh -c 'rake generate:build[$LANG]'

trigger:
  schedules:
  - name: daily
    cron: '30 11 * * *' ## daily at 11:30am
    branch: master
